### ISSUE TITLE
08_Duckling.ipynb - TypeError

### ISSUE THREAD

**Issue by sony-au** [practical-nlp/practical-nlp#10]
Hi, I've been trying to run the below code on Jupyter Notebook and Colab, but both threw the same error:

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-5-89ccdbf1af8f> in <module>()
----> 1 pprint(d.parse_time(u"Let\'s meet at 11:45am"))
      2 #pprint(d.parse_time(u'You owe me twenty bucks, please call me today'))

4 frames

/usr/local/lib/python3.6/dist-packages/jpype/_jstring.py in __getitem__(self, i)
     46 
     47     def __getitem__(self, i):
---> 48         if i < 0:
     49             i += len(self)
     50             if i < 0:

TypeError: '<' not supported between instances of 'slice' and 'int'

I tried duckling 1.8.0, and 1.7.1, without success. I was wondering if anyone could point me in the right direction? Thank you.

Regards,
Sony

**Comment by varunp2k** [comment]
Hi  @sony-au,
Thank you for bringing this to our notice. We are looking into this. Will get back to you.

Regards,
Practical NLP Team

**Comment by nishkalavallabhi** [comment]
@sony-au @varunp2k  - I just ran this with Duckling 1.8.0, but with old Python version (3.6), on Ubuntu and with Jupyter Notebook. I was able to run it without errors.

**Comment by varunp2k** [comment]
@sony-au The issue seems to be because of issue with openjdk. It does not work for openjdk 11 but works for openjdk version 8. We have opened an issue in the  git repo of Duckling package too.

**Comment by sony-au** [comment]
@varunp2k @nishkalavallabhi I installed JPype 0.7.4 and it resolved the issue. it did show the deprecation warning, but it works. thanks guys

**Comment by Thrameos** [comment]
This issue is because the library in question is depending on the deprecated JPype automatic conversion for Java strings to Python strings.  Simply adding a call to `str()` prior to getting the slice will correct the issue as it will transfer the string from Java to Python where slightly different operators are supported.   Slicing is not supported on a Java string but is on a Python string.

ie.  Before
```
    a = callSomething()[1:5]  # worked on old because callSomething returned a Python string.
``

After
```
    a = str(callSomething())[1:5]  # works on both old and new JPype
```

If the code has way too many of these to fix add "convertStrings=True" to the startJVM command.  It will give the old behavior.  ConvertStrings will make the code incompatible with other JPype libraries but should also fix the issue.  There has been a deprecated warning on this for the last year (so you can't say you weren't warned).  The warning was supposed to tell you to either add ``convertStrings=True`` and force the old behavior or ``convertStrings=False`` which would lead to fixing the bad code.

If possible please correct the error rather than rolling back the JPype version.   I work to fix leaks and improve code quality and freezing the version to something old just makes it so people are getting older bugger code.

**Comment by varunp2k** [comment]
We are not interacting directly with the JPype library. Ducking is doing that. The reason we recommend rolling back the version is because Ducking has not been updated since a few years. It has been inactive.
Plus the greater goal at hand here is people being able to run the ducking notebook and understand how it implements Temporal IE. We understand that the way which we recommend is not optimal, but again as mentioned Ducking is not actively maintained and hence we need to use a JPype version which is compatible with it.

We understand the importance of code quality, using the latest and improved versions of the code. But this repository serves as a aid/tutorial for the readers of the book. It is a bit hard from our end to keep updating the code for every version change from packages. That is the reason we are freezing the versions of packages.

**Comment by Thrameos** [comment]
I attempted to address the issue with jpype-project/jpype#833 which will add slicing support for the string wrapper.  After all it much easier to  the active project to address the issue that the inactive one.   Unfortunately, as I don't run ducking I don't know what other issues are lurking here.  You would need to test with the software and see if addresses all the issues.

As a book i understand the desire to pin rather than tracking the latest software. though if I can help get this up to date rather than pin at a potentially old version it would be best.  It is much worse when it is a library such as JayDeBeAPI which people are intended to build code on which is pinning to an ancient version.  That generates a poor experience for both my users and results in me having to answer questions from times before I joined JPype on problems long since fixed.
